name: ğŸ“Š AnÃ¡lise PRF 2024 | ğŸ§¬ EstatÃ­stica e Probabilidade Unidade I

# Define quais eventos disparam a execuÃ§Ã£o automÃ¡tica.
on:
  push:
    branches:
      -  main  # Em novos commits para a branch main
  pull_request:
    types: [ opened, synchronize, reopened ] # Em pull requests para a branch main

jobs:
  build:
    # Maquina virtual onde a aÃ§Ã£o serÃ¡ executada
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do cÃ³digo para a mÃ¡quina virtual
      - name: "ğŸ“‚ Sincronizando RepositÃ³rio"
        uses: actions/checkout@v4

      # 2. Configura o ambiente R 4.5.2
      - name: "âš™ï¸ Configurando Engine R (4.5.2)"
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.2' # Minha versÃ£o especÃ­fica do R

      # 3. Gerenciamento e instalaÃ§Ã£o de pacotes necessÃ¡rios
      - name: "ğŸ“¦ Instalando Bibliotecas (dplyr, ggplot2, scales, tidyr, testthat)"
        run: |
          install.packages(c("dplyr", "ggplot2", "scales", "tidyr", "testthat"), repos = "https://cloud.r-project.org/")
        shell: Rscript {0}

      # 4. Executa o script principal de anÃ¡lise (inclui anÃ¡lises + testes + grÃ¡ficos)
      - name: "ğŸš€ Executando AnÃ¡lise EstatÃ­stica"
        run: |
          source("scripts/main.R")
        shell: Rscript {0}

      # 5. Salva os grÃ¡ficos gerados como artefatos de build
      - name: "ğŸ–¼ï¸ Salvando Resultados (GrÃ¡ficos)"
        uses: actions/upload-artifact@v4
        with:
          name: "Relatorio_Visual_PRF"
          path: graficos/*.png
